(function(){
'use strict';
function load(src){return new Promise(function(resolve,reject){var s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]});}
async function start(){
  try{
    if(!window.CHESS_FIREBASE_CONFIG){await load('./firebase-config.js');}
    await load('https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js');
    await load('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth-compat.js');
    await load('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore-compat.js');
    firebase.initializeApp(window.CHESS_FIREBASE_CONFIG);
    var auth=firebase.auth(), db=firebase.firestore();
    window.chessFirebase={auth:auth,db:db};
    addStyles(); addUI(auth,db); auth.onAuthStateChanged(function(u){renderAuth(u,auth,db);});
  }catch(e){console.error('Firebase:',e);}
}
function addStyles(){if(document.getElementById('fb-style'))return;var s=document.createElement('style');s.id='fb-style';s.textContent='.fb-btn{border:1px solid var(--line);background:#111d32;color:var(--text);padding:9px 12px;border-radius:10px;cursor:pointer;font-weight:700}.fb-panel{position:fixed;right:18px;top:82px;width:min(360px,calc(100vw - 36px));z-index:1000;background:#0d1728f7;border:1px solid var(--line);border-radius:18px;padding:16px;box-shadow:0 25px 80px #000b;display:none}.fb-panel.open{display:block}.fb-input{width:100%;padding:10px;border-radius:10px;border:1px solid var(--line);background:#091322;color:#fff;margin:5px 0 9px}.fb-actions{display:flex;gap:7px;flex-wrap:wrap}.fb-msg{margin:9px 0;color:var(--muted);font-size:13px}.online-page{display:none}.online-page.active{display:block}.online-grid{display:grid;grid-template-columns:minmax(420px,1fr) 350px;gap:20px}.online-board{width:min(100%,700px);aspect-ratio:1;display:grid;grid-template-columns:repeat(8,1fr);margin:auto;border:4px solid #1d2a42;border-radius:14px;overflow:hidden}.online-sq{display:grid;place-items:center;border:0;font-size:clamp(28px,7vw,62px);cursor:pointer}.online-light{background:#f0d9b5}.online-dark{background:#b58863}.online-selected{box-shadow:inset 0 0 0 5px #ffe36d}.online-legal{outline:4px solid #7857ff88;outline-offset:-8px}.online-piece{line-height:1}.online-card{background:linear-gradient(145deg,#142036f2,#0d1627f2);border:1px solid var(--line);border-radius:20px;padding:18px}.fb-profile{display:flex;align-items:center;gap:8px}.fb-elo{font-weight:900;color:#c4b5fd}.online-moves{max-height:350px;overflow:auto;margin-top:12px}.online-move{padding:6px;border-bottom:1px solid #223049}.fb-code{font-size:24px;letter-spacing:4px;font-weight:900;text-align:center;padding:12px;background:#091322;border-radius:10px;margin:10px 0}.fb-hidden{display:none!important}';document.head.appendChild(s)}
function addUI(auth,db){
  var nav=document.querySelector('nav'); if(!nav)return;
  var b=document.createElement('button');b.className='tab';b.textContent='🌐 En ligne';b.dataset.page='online';nav.appendChild(b);
  var account=document.createElement('button');account.className='fb-btn';account.id='fbAccount';account.textContent='Connexion';document.querySelector('.top').appendChild(account);
  var panel=document.createElement('div');panel.id='fbPanel';panel.className='fb-panel';document.body.appendChild(panel);
  account.onclick=function(){panel.classList.toggle('open');};
  var page=document.createElement('main');page.id='online';page.className='page online-page';page.innerHTML='<div class="online-grid"><section class="online-card"><div id="onlineBoard" class="online-board"></div><div class="status"><b id="onlineStatus">Connectez-vous pour jouer</b><span id="onlinePlayers" class="muted"></span></div><div class="controls"><button class="btn" id="onlineNew">Nouvelle partie</button><button class="btn" id="onlineLeave">Quitter</button></div></section><aside class="online-card"><h2>Multijoueur</h2><div id="onlineLobby"></div><div id="onlineMoves" class="online-moves"></div></aside></div>';
  document.querySelector('.app').insertBefore(page,document.querySelector('.footer'));
  b.onclick=function(){document.querySelectorAll('.tab').forEach(function(x){x.classList.toggle('active',x===b)});document.querySelectorAll('.page').forEach(function(x){x.classList.toggle('active',x.id==='online')});};
  document.getElementById('onlineNew').onclick=function(){createGame(auth,db)};
  document.getElementById('onlineLeave').onclick=function(){leaveGame(auth,db)};
}
function renderAuth(user,auth,db){
  var a=document.getElementById('fbAccount'),p=document.getElementById('fbPanel');if(!a||!p)return;
  if(user){a.textContent='👤 '+(user.displayName||user.email.split('@')[0]);p.innerHTML='<div class="fb-profile"><b>'+esc(user.displayName||user.email)+'</b></div><div class="fb-msg" id="fbProfileMsg">Chargement du profil…</div><div class="fb-actions"><button class="fb-btn" id="fbLogout">Déconnexion</button></div>';document.getElementById('fbLogout').onclick=function(){auth.signOut()};ensureProfile(user,db);}
  else{a.textContent='Connexion';p.innerHTML='<h3>Compte</h3><input class="fb-input" id="fbName" placeholder="Pseudo"><input class="fb-input" id="fbEmail" type="email" placeholder="Email"><input class="fb-input" id="fbPass" type="password" placeholder="Mot de passe (6 caractères min.)"><div class="fb-actions"><button class="fb-btn" id="fbRegister">Créer un compte</button><button class="fb-btn" id="fbLogin">Se connecter</button></div><div class="fb-msg" id="fbMsg"></div>';document.getElementById('fbRegister').onclick=function(){register(auth,db)};document.getElementById('fbLogin').onclick=function(){login(auth)};}
  renderLobby(auth,db);
}
function register(auth,db){var n=document.getElementById('fbName').value.trim(),e=document.getElementById('fbEmail').value.trim(),pw=document.getElementById('fbPass').value,m=document.getElementById('fbMsg');if(!n||!e||pw.length<6){m.textContent='Pseudo, email et mot de passe (6+) requis.';return}auth.createUserWithEmailAndPassword(e,pw).then(function(c){return c.user.updateProfile({displayName:n}).then(function(){return ensureProfile(c.user,db)})}).catch(function(x){m.textContent=x.message});}
function login(auth){var e=document.getElementById('fbEmail').value.trim(),pw=document.getElementById('fbPass').value,m=document.getElementById('fbMsg');auth.signInWithEmailAndPassword(e,pw).catch(function(x){m.textContent=x.message});}
function ensureProfile(user,db){var ref=db.collection('users').doc(user.uid);return ref.get().then(function(s){if(!s.exists)return ref.set({username:user.displayName||user.email.split('@')[0],email:user.email,elo:1000,wins:0,losses:0,draws:0,createdAt:firebase.firestore.FieldValue.serverTimestamp()});}).then(function(){var m=document.getElementById('fbProfileMsg');if(m)return ref.get().then(function(s){var d=s.data()||{};m.innerHTML='Elo <span class="fb-elo">'+(d.elo||1000)+'</span> · '+(d.wins||0)+'V / '+(d.losses||0)+'D / '+(d.draws||0)+'N';});});}
function renderLobby(auth,db){var l=document.getElementById('onlineLobby');if(!l)return;var u=auth.currentUser;if(!u){l.innerHTML='<p class="muted">Connectez-vous pour créer ou rejoindre une partie.</p>';return}l.innerHTML='<p class="muted">Créez une partie puis partagez le code à votre adversaire.</p><input class="fb-input" id="joinCode" placeholder="Code de partie"><div class="fb-actions"><button class="fb-btn" id="joinGame">Rejoindre</button></div><div id="gameCode"></div>';document.getElementById('joinGame').onclick=function(){joinGame(auth,db)};}
function createGame(auth,db){var u=auth.currentUser;if(!u){alert('Connectez-vous d’abord.');return}var code=Math.random().toString(36).slice(2,8).toUpperCase();var ref=db.collection('games').doc(code);ref.set({code:code,white:u.uid,whiteName:u.displayName||u.email.split('@')[0],black:null,blackName:null,fen:'start',pgn:'',turn:'w',status:'waiting',createdAt:firebase.firestore.FieldValue.serverTimestamp()}).then(function(){watchGame(ref,auth,db);showCode(code);});}
function showCode(code){var x=document.getElementById('gameCode');if(x)x.innerHTML='<div class="fb-code">'+esc(code)+'</div><div class="muted">Partagez ce code avec votre adversaire.</div>';}
function joinGame(auth,db){var u=auth.currentUser,code=(document.getElementById('joinCode').value||'').trim().toUpperCase();if(!u||!code)return;var ref=db.collection('games').doc(code);ref.get().then(function(s){if(!s.exists){alert('Partie introuvable.');return}var d=s.data();if(d.white===u.uid||d.black===u.uid){watchGame(ref,auth,db);return}if(d.black){alert('Partie complète.');return}return ref.update({black:u.uid,blackName:u.displayName||u.email.split('@')[0],status:'playing'}).then(function(){watchGame(ref,auth,db)});});}
var currentGameRef=null,currentOnlineGame=null,currentOnline=null,onlineSelected=null;
function watchGame(ref,auth,db){currentGameRef=ref;ref.onSnapshot(function(s){if(!s.exists)return;currentOnlineGame=s.data();if(currentOnlineGame.fen==='start'){currentOnline=new Chess();}else{currentOnline=new Chess(currentOnlineGame.fen)};onlineSelected=null;renderOnlineBoard(auth);renderOnlineMoves();var u=auth.currentUser,side=u&&u.uid===currentOnlineGame.white?'w':u&&u.uid===currentOnlineGame.black?'b':null;document.getElementById('onlineStatus').textContent=currentOnlineGame.status==='waiting'?'En attente de l’adversaire…':currentOnlineGame.status==='finished'?'Partie terminée':(side===currentOnlineGame.turn?'À vous de jouer':'Tour de l’adversaire');document.getElementById('onlinePlayers').textContent=(currentOnlineGame.whiteName||'?')+' vs '+(currentOnlineGame.blackName||'…');showCode(currentOnlineGame.code);});}
function renderOnlineBoard(auth){var el=document.getElementById('onlineBoard');if(!el||!currentOnline)return;el.innerHTML='';var u=auth.currentUser,side=u&&u.uid===currentOnlineGame.black?'b':'w',files=side==='w'?'abcdefgh':'hgfedcba',ranks=side==='w'?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8],sel=onlineSelected,legal=sel?currentOnline.moves({square:sel,verbose:true}):[];var uni={p:{w:'♙',b:'♟'},n:{w:'♘',b:'♞'},b:{w:'♗',b:'♝'},r:{w:'♖',b:'♜'},q:{w:'♕',b:'♛'},k:{w:'♔',b:'♚'}};for(var r=0;r<8;r++)for(var c=0;c<8;c++){var sq=files[c]+ranks[r],q=document.createElement('button');q.className='online-sq '+(((FILES.indexOf(files[c])+ranks[r])%2===0)?'online-light':'online-dark');if(sq===sel)q.classList.add('online-selected');if(legal.some(function(m){return m.to===sq}))q.classList.add('online-legal');var p=currentOnline.get(sq);if(p)q.innerHTML='<span class="online-piece">'+uni[p.type][p.color]+'</span>';q.onclick=function(s){return function(){onlineClick(s,auth)}}(sq);el.appendChild(q);}}
function onlineClick(s,auth){if(!currentOnline||!currentGameRef||!currentOnlineGame||currentOnlineGame.status!=='playing')return;var u=auth.currentUser;if(!u)return;var side=u.uid===currentOnlineGame.white?'w':u.uid===currentOnlineGame.black?'b':null;if(side!==currentOnline.turn)return;if(!onlineSelected){var p=currentOnline.get(s);if(p&&p.color===side){onlineSelected=s;renderOnlineBoard(auth)}return}var m=currentOnline.move({from:onlineSelected,to:s,promotion:'q'});onlineSelected=null;if(!m){renderOnlineBoard(auth);return}var fen=currentOnline.fen(),pgn=currentOnline.pgn();var result=currentOnline.isGameOver()? (currentOnline.isCheckmate()?(side==='w'?'1-0':'0-1'):'1/2-1/2'):null;currentGameRef.update({fen:fen,pgn:pgn,turn:currentOnline.turn(),status:result?'finished':'playing',result:result||null}).catch(function(e){console.error(e)});}
function renderOnlineMoves(){var el=document.getElementById('onlineMoves');if(!el||!currentOnline)return;el.innerHTML='';currentOnline.history().forEach(function(m,i){var d=document.createElement('div');d.className='online-move';d.textContent=(i+1)+'. '+m;el.appendChild(d)});}
function leaveGame(auth,db){if(currentGameRef){currentGameRef.update({status:'finished'}).catch(function(){});currentGameRef=null;currentOnlineGame=null;currentOnline=null;document.getElementById('onlineBoard').innerHTML='';document.getElementById('onlineMoves').innerHTML='';document.getElementById('onlineStatus').textContent='Connectez-vous pour jouer';}}
start();
})();
