(function(){'use strict';
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function init(auth,db){
 if(document.getElementById('matchmakingTab'))return;
 var nav=document.querySelector('nav');if(!nav)return;
 var tab=document.createElement('button');tab.id='matchmakingTab';tab.className='tab';tab.dataset.page='matchmaking';tab.textContent='⚡ Matchmaking';nav.appendChild(tab);
 var page=document.createElement('main');page.id='matchmaking';page.className='page';page.innerHTML='<section class="card"><h2>⚡ Matchmaking</h2><p class="muted">Trouve automatiquement un adversaire proche de ton Elo.</p><div id="mmElo" class="result">— Elo</div><div class="controls"><button class="btn primary" id="mmFind">Trouver une partie</button><button class="btn" id="mmCancel" style="display:none">Annuler</button></div><div id="mmStatus" class="result">Prêt.</div><div id="mmOpponent"></div></section>';
 document.querySelector('.app').insertBefore(page,document.querySelector('.footer'));
 tab.onclick=function(){document.querySelectorAll('.tab').forEach(function(x){x.classList.toggle('active',x===tab)});document.querySelectorAll('.page').forEach(function(x){x.classList.toggle('active',x===page)})};
 var find=page.querySelector('#mmFind'),cancel=page.querySelector('#mmCancel'),status=page.querySelector('#mmStatus'),eloEl=page.querySelector('#mmElo'),unsub=null;
 auth.onAuthStateChanged(function(u){if(!u){eloEl.textContent='Connecte-toi';return}db.collection('users').doc(u.uid).get().then(function(s){eloEl.textContent=(s.data()&&s.data().elo||1000)+' Elo'}).catch(function(){eloEl.textContent='Elo indisponible'})});
 function openMatchedGame(code){window.dispatchEvent(new CustomEvent('chess-match-found',{detail:{code:code}}));var onlineTab=document.querySelector('.tab[data-page="online"]');if(onlineTab)onlineTab.click()}
 find.onclick=function(){var u=auth.currentUser;if(!u){status.textContent='Connecte-toi pour utiliser le matchmaking.';return}find.disabled=true;cancel.style.display='inline-block';status.textContent='Recherche d’un adversaire…';var ref=db.collection('matchmaking').doc(u.uid);db.collection('users').doc(u.uid).get().then(function(us){var d=us.data()||{},elo=d.elo||1000;return ref.set({uid:u.uid,username:d.username||u.displayName||'Joueur',elo:elo,createdAt:firebase.firestore.FieldValue.serverTimestamp(),active:true})}).then(function(){unsub=db.collection('matchmaking').onSnapshot(function(snap){var candidates=snap.docs.filter(function(d){var x=d.data();return d.id!==u.uid&&x.active===true});if(!candidates.length)return;db.collection('users').doc(u.uid).get().then(function(us){var me=us.data()||{},elo=me.elo||1000;candidates.sort(function(a,b){return Math.abs((a.data().elo||1000)-elo)-Math.abs((b.data().elo||1000)-elo)});var opp=candidates[0],o=opp.data();if(Math.abs((o.elo||1000)-elo)>300)return;var code=Math.random().toString(36).slice(2,8).toUpperCase(),white=Math.random()<.5?u.uid:o.uid,black=white===u.uid?o.uid:u.uid;db.collection('games').doc(code).set({code:code,white:white,black:black,whiteName:white===u.uid?(me.username||u.displayName||'Joueur'):(o.username||'Adversaire'),blackName:black===u.uid?(me.username||u.displayName||'Joueur'):(o.username||'Adversaire'),fen:'start',pgn:'',turn:'w',status:'playing',mode:'matchmaking',whiteElo:white===u.uid?elo:o.elo,blackElo:black===u.uid?elo:o.elo,createdAt:firebase.firestore.FieldValue.serverTimestamp()}).then(function(){ref.delete().catch(function(){});db.collection('matchmaking').doc(o.uid).delete().catch(function(){});if(unsub)unsub();find.disabled=false;cancel.style.display='none';status.innerHTML='Partie trouvée ! <b>'+esc(o.username||'Adversaire')+'</b> · '+(o.elo||1000);page.querySelector('#mmOpponent').innerHTML='<div class="result">Partie : <b>'+esc(code)+'</b><br><button class="btn primary" id="openMatched">Jouer maintenant</button></div>';var open=page.querySelector('#openMatched');if(open)open.onclick=function(){openMatchedGame(code)};openMatchedGame(code)})})})}).catch(function(e){find.disabled=false;cancel.style.display='none';status.textContent='Erreur : '+e.message})};
 cancel.onclick=function(){var u=auth.currentUser;if(unsub)unsub();if(u)db.collection('matchmaking').doc(u.uid).delete().catch(function(){});find.disabled=false;cancel.style.display='none';status.textContent='Recherche annulée.'};
 window.startChessMatchmaking=function(){tab.click()};
}
window.initChessMatchmaking=init;
})();