(function(){'use strict';
var current=null,unsub=null,selected=null,game=null,auth=null,db=null,started=false;
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function isGameOver(){return !!game&&(typeof game.isGameOver==='function'?game.isGameOver():typeof game.game_over==='function'?game.game_over():false)}
function init(a,d){if(started)return;started=true;auth=a;db=d;var page=document.getElementById('online');if(!page)return;var boardWrap=document.createElement('div');boardWrap.id='onlineGameArea';boardWrap.innerHTML='<div class="layout"><section class="card"><div id="onlineBoard" class="board"></div><div id="onlineGameStatus" class="status"></div><div class="controls"><button class="btn" id="onlineBack">← Parties</button><button class="btn" id="onlineCopy">Copier PGN</button></div></section><aside class="card"><h2>Partie en ligne</h2><div id="onlineGameInfo" class="result"></div><div id="onlineMoves" class="moves"></div></aside></div>';boardWrap.style.display='none';page.appendChild(boardWrap);
var create=document.getElementById('createGame'),find=document.getElementById('findGame');if(create)create.onclick=createGame;if(find)find.onclick=function(){var tab=document.querySelector('.tab[data-page="matchmaking"]');if(tab)tab.click();else if(window.startChessMatchmaking)window.startChessMatchmaking()};
var back=document.getElementById('onlineBack');if(back)back.onclick=function(){closeGame();showLobby()};var copy=document.getElementById('onlineCopy');if(copy)copy.onclick=function(){if(!game)return;var text=game.pgn(),done=function(){copy.textContent='✓ PGN copié';setTimeout(function(){copy.textContent='Copier PGN'},1200)};if(navigator.clipboard)navigator.clipboard.writeText(text).then(done);};
auth.onAuthStateChanged(function(u){if(u)listGames();else setLobbyStatus('Connectez-vous pour jouer en ligne.')});listGames();window.addEventListener('chess-match-found',function(e){if(e.detail&&e.detail.code)openGame(e.detail.code)});}
function setLobbyStatus(t){var x=document.getElementById('onlineStatus');if(x)x.textContent=t}
function showLobby(){document.getElementById('onlineGameArea').style.display='none';var list=document.getElementById('onlineGames');if(list)list.style.display='block';listGames()}
function createGame(){var u=auth.currentUser;if(!u){setLobbyStatus('Connectez-vous pour créer une partie.');return}var code=Math.random().toString(36).slice(2,8).toUpperCase();db.collection('users').doc(u.uid).get().then(function(s){var d=s.data()||{};return db.collection('games').doc(code).set({code:code,white:u.uid,black:null,whiteName:d.username||u.displayName||'Joueur',blackName:null,fen:'start',pgn:'',turn:'w',status:'waiting',mode:'online',createdAt:firebase.firestore.FieldValue.serverTimestamp()})}).then(function(){openGame(code)}).catch(function(e){setLobbyStatus('Erreur : '+e.message)})}
function listGames(){var list=document.getElementById('onlineGames');if(!list||!db)return;db.collection('games').where('status','==','waiting').limit(20).onSnapshot(function(snap){var u=auth.currentUser;var html='<h3>Parties disponibles</h3>';snap.forEach(function(doc){var d=doc.data();if(!u||d.white===u.uid)return;html+='<div class="result" style="margin:8px 0;display:flex;justify-content:space-between;align-items:center"><span><b>'+esc(d.whiteName||'Joueur')+'</b> · '+esc(doc.id)+'</span><button class="btn primary join-game" data-code="'+esc(doc.id)+'">Rejoindre</button></div>'});list.innerHTML=html;list.querySelectorAll('.join-game').forEach(function(b){b.onclick=function(){joinGame(b.dataset.code)}})},function(e){setLobbyStatus('Impossible de charger les parties : '+e.message)})}
function joinGame(code){var u=auth.currentUser;if(!u)return;db.collection('users').doc(u.uid).get().then(function(s){var d=s.data()||{};return db.collection('games').doc(code).update({black:u.uid,blackName:d.username||u.displayName||'Joueur',status:'playing'})}).then(function(){openGame(code)}).catch(function(e){setLobbyStatus('Impossible de rejoindre : '+e.message)})}
function openGame(code){var u=auth.currentUser;if(!u)return;var ref=db.collection('games').doc(code);ref.get().then(function(s){if(!s.exists){setLobbyStatus('Partie introuvable.');return}var d=s.data();if(d.white!==u.uid&&d.black!==u.uid){setLobbyStatus('Vous ne participez pas à cette partie.');return}current={code:code,ref:ref,white:d.white,black:d.black};game=new Chess();if(d.fen&&d.fen!=='start')game.load(d.fen);selected=null;document.getElementById('onlineGames').style.display='none';document.getElementById('onlineGameArea').style.display='block';if(unsub)unsub();unsub=ref.onSnapshot(function(s){if(!s.exists)return;var x=s.data();current.white=x.white;current.black=x.black;if(x.fen&&x.fen!=='start'&&x.fen!==game.fen())game.load(x.fen);render();if(x.status==='finished')setStatus('Partie terminée');else if(x.status==='waiting')setStatus('En attente d’un adversaire…')});render()})}
function render(){var el=document.getElementById('onlineBoard');if(!el||!game)return;el.innerHTML='';var files='abcdefgh',ranks='87654321';for(var ri=0;ri<8;ri++)for(var fi=0;fi<8;fi++){var sq=files[fi]+ranks[ri],p=game.get(sq),b=document.createElement('button');b.type='button';b.className='sq '+((fi+ri)%2?'dark':'light');b.dataset.square=sq;if(p){var piece=p.type==='p'?'♟':p.type==='n'?'♞':p.type==='b'?'♝':p.type==='r'?'♜':p.type==='q'?'♛':'♚';b.textContent=piece;b.style.color=p.color==='w'?'#fff':'#111';b.style.textShadow=p.color==='w'?'0 1px 3px #000':'0 1px 3px #fff'}b.onclick=function(){play(this.dataset.square)};el.appendChild(b)}var h=game.history({verbose:true}),mv=document.getElementById('onlineMoves');if(mv)mv.innerHTML=h.reduce(function(s,m,i){return i%2===0?s+'<div class="move"><b>'+((i/2)+1)+'.</b><span>'+m.san+'</span><span>'+(h[i+1]?h[i+1].san:'')+'</span></div>':s},'');var u=auth.currentUser,side=u&&(u.uid===current.white?'w':u.uid===current.black?'b':null);if(side&&game.turn()===side&&!isGameOver())setStatus(side==='w'?'À vous — Blancs':'À vous — Noirs');else if(side)setStatus(isGameOver()?'Partie terminée':'Tour de l’adversaire')}
function setStatus(t){var x=document.getElementById('onlineGameStatus');if(x)x.textContent=t;var info=document.getElementById('onlineGameInfo');if(info&&current)info.innerHTML='<b>Code : '+esc(current.code)+'</b><br>Blancs : '+esc(current.white||'—')+'<br>Noirs : '+esc(current.black||'En attente…')}
function play(sq){var u=auth.currentUser;if(!u||!current||!game)return;var side=u.uid===current.white?'w':u.uid===current.black?'b':null;if(!side||game.turn()!==side||isGameOver())return;var p=game.get(sq);if(!selected){if(p&&p.color===side){selected=sq;render();return}}else{var from=selected;var move=game.move({from:from,to:sq,promotion:'q'});selected=null;if(!move){if(p&&p.color===side)selected=sq;render();return}var status=isGameOver()?'finished':'playing';current.ref.update({fen:game.fen(),pgn:game.pgn(),turn:game.turn(),lastMove:{from:from,to:sq,san:move.san,at:Date.now()},status:status}).catch(function(e){setStatus('Erreur de synchronisation : '+e.message)});render()}}
function closeGame(){if(unsub){unsub();unsub=null}current=null;game=null;selected=null}
window.initChessMultiplayer=init;window.openChessOnlineGame=openGame;window.addEventListener('chess-firebase-ready',function(){if(window.chessFirebase)init(window.chessFirebase.auth,window.chessFirebase.db)});if(window.chessFirebase&&window.chessFirebase.ready)init(window.chessFirebase.auth,window.chessFirebase.db);
})();