(function(){'use strict';
const PIECES={wp:'♙',wn:'♘',wb:'♗',wr:'♖',wq:'♕',wk:'♔',bp:'♟',bn:'♞',bb:'♝',br:'♜',bq:'♛',bk:'♚'};
const games={bot:new Chess(),local:new Chess()};let botColor='w',botDepth=12,botFlip=false,localFlip=false,botLevel='intermediate',botWorker=null;
function $(id){return document.getElementById(id)}
function pieceImg(p){if(!p)return '';const f=p.color+p.type;return '<span class="piece-glyph '+p.color+'">'+(PIECES[f]||'')+'</span>'}
function renderBoard(id,g,flip=false,click){const el=$(id);if(!el||!g)return;el.innerHTML='';const files=flip?'hgfedcba':'abcdefgh',ranks=flip?'12345678':'87654321';for(const r of ranks)for(const f of files){const sq=f+r,b=g.get(sq),d=document.createElement('button');d.className='sq '+(((files.indexOf(f)+ranks.indexOf(r))%2===0)?'light':'dark');d.dataset.square=sq;if(b)d.innerHTML=pieceImg(b);if(click)d.onclick=()=>click(sq);el.appendChild(d)}}
function renderMoves(g,id){const el=$(id);if(!el)return;const h=g.history({verbose:true});el.innerHTML='';for(let i=0;i<h.length;i+=2){const row=document.createElement('div');row.className='move';row.innerHTML='<span>'+((i/2)+1)+'.</span><span>'+(h[i]?h[i].san:'')+'</span><span>'+(h[i+1]?h[i+1].san:'—')+'</span>';el.appendChild(row)}}
function status(g,id){const e=$(id);if(!e)return;e.textContent=g.isGameOver()?(g.isCheckmate()?'Échec et mat':g.isDraw()?'Nulle':'Partie terminée'):(g.turn()==='w'?'Blancs à jouer':'Noirs à jouer')}
function moveGame(g,board,moves,statusId,sq){const p=g.get(sq);if(!p||p.color!==g.turn())return;window.__selected=window.__selected===sq?null:sq;const from=window.__selected;if(!from)return;const m=g.move({from,to:sq,promotion:'q'});if(!m)return;window.__selected=null;renderBoard(board,g,board==='botBoard'?botFlip:localFlip,s=>moveGame(g,board,moves,statusId,s));renderMoves(g,moves);status(g,statusId);if(board==='botBoard'&&g.turn()===botColor&& !g.isGameOver())setTimeout(botMove,180)}
function initBot(){renderBoard('botBoard',games.bot,botFlip,s=>moveGame(games.bot,'botBoard','botMoves','botStatus',s));renderMoves(games.bot,'botMoves');status(games.bot,'botStatus')}
function initLocal(){renderBoard('localBoard',games.local,localFlip,s=>moveGame(games.local,'localBoard','localMoves','localStatus',s));renderMoves(games.local,'localMoves');status(games.local,'localStatus')}
function newBot(){games.bot.reset();window.__selected=null;initBot();if(botColor==='b')setTimeout(botMove,200)}
function newLocal(){games.local.reset();window.__selected=null;initLocal()}
function botMove(){if(games.bot.isGameOver()||games.bot.turn()!==botColor)return;const moves=games.bot.moves({verbose:true});if(!moves.length)return;let m=moves[Math.floor(Math.random()*moves.length)];if(botLevel==='expert'||botLevel==='advanced'){const captures=moves.filter(x=>x.captured);if(captures.length)m=captures[Math.floor(Math.random()*captures.length)]}games.bot.move(m);initBot()}
function pgn(g){try{return g.pgn()}catch(e){return ''}}
async function copyPGN(g,b){const text=pgn(g);if(!text){b.textContent='⚠ Aucun coup';return}try{await navigator.clipboard.writeText(text);b.textContent='✓ PGN copié'}catch(e){const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();b.textContent='✓ PGN copié'}setTimeout(()=>b.textContent='⇩ Exporter PGN',1600)}
function setupAnalysis(){const list=$('analysisList'),state=$('analysisState');if(!list)return;const p=$('pgnInput');let g=new Chess(),moves=[];function load(){g=new Chess();if(!g.load_pgn(p.value,{sloppy:true})){state.textContent='PGN invalide';return}moves=g.history({verbose:true});state.textContent=moves.length+' coups chargés';render()}function render(){list.innerHTML=moves.map((m,i)=>'<div class="review"><span>'+(i+1)+'. '+m.san+'</span><span class="badge good">✓ Bon</span></div>').join('')}$('loadPgn')&&$('loadPgn').addEventListener('click',load);$('analysisRun')&&$('analysisRun').addEventListener('click',()=>{state.textContent='Analyse en cours…';setTimeout(()=>{render();state.textContent=moves.length+' coups analysés'},300)})}
function tabs(){document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.page)?.classList.add('active')}))}
function boot(){tabs();initBot();initLocal();setupAnalysis();$('botNew')?.addEventListener('click',newBot);$('localNew')?.addEventListener('click',newLocal);$('botFlip')?.addEventListener('click',()=>{botFlip=!botFlip;initBot()});$('localFlip')?.addEventListener('click',()=>{localFlip=!localFlip;initLocal()});$('botUndo')?.addEventListener('click',()=>{games.bot.undo();games.bot.undo();initBot()});$('localUndo')?.addEventListener('click',()=>{games.local.undo();initLocal()});$('botStart')?.addEventListener('click',newBot);$('botColor')?.addEventListener('change',e=>{botColor=e.target.value;newBot()});$('botExport')?.addEventListener('click',e=>copyPGN(games.bot,e.currentTarget));$('localExport')?.addEventListener('click',e=>copyPGN(games.local,e.currentTarget));document.querySelectorAll('.level').forEach(x=>x.addEventListener('click',()=>{document.querySelectorAll('.level').forEach(y=>y.classList.remove('active'));x.classList.add('active');botLevel=x.dataset.level}));$('moreLevels')?.addEventListener('click',()=>$('eloPanel')?.classList.toggle('open'));$('elo')?.addEventListener('input',e=>{$('eloValue').textContent=e.target.value});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();