(function(){'use strict';
const BOT_LEVELS={400:{name:'Débutant',depth:1,random:0.95},600:{name:'Novice',depth:1,random:0.8},800:{name:'Apprenti',depth:2,random:0.65},1000:{name:'Intermédiaire',depth:2,random:0.45},1200:{name:'Confirmé',depth:2,random:0.3},1400:{name:'Club',depth:3,random:0.25},1600:{name:'Avancé',depth:3,random:0.18},1800:{name:'Fort',depth:4,random:0.12},2000:{name:'Expert',depth:4,random:0.08},2200:{name:'Maître',depth:5,random:0.05},2400:{name:'Maître fort',depth:5,random:0.035},2600:{name:'Élite',depth:6,random:0.025},2800:{name:'Grand maître',depth:7,random:0.015},3000:{name:'Super GM',depth:8,random:0.008}};
const ICONS={p:'M12 3c-2 0-3 1.5-3 3 0 1.1.6 2 1.5 2.6C8.5 10 7 12 7 14h10c0-2-1.5-4-3.5-5.4C14.4 8 15 7.1 15 6c0-1.5-1-3-1-3zm-6 13h12v2H6z',n:'M7 19h10v-2H9c0-3 2-5 6-7l-2-6H8l-2 4 3 2c-3 2-4 5-4 9z',b:'M12 3c-3 2-5 5-5 8 0 2 1 3 3 4H7v2h10v-2h-3c2-1 3-2 3-4 0-3-2-6-5-8zm0 3c1.4 1.7 2.3 3.3 2.3 5H9.7c0-1.7.9-3.3 2.3-5z',r:'M6 3h12v3h-2v7h2v4H6v-4h2V6H6z',q:'M5 5l2 3 5-5 5 5 2-3-2 10H7zM6 17h12v2H6z',k:'M11 2h2v3h3v2h-3v3h4v7H7v-7h4V7H8V5h3zm-2 12v3h6v-3z'};
const state={bot:new Chess(),local:new Chess(),analysis:new Chess(),puzzle:new Chess(),selected:null,botColor:'w',flip:{bot:false,local:false,analysis:false,puzzle:false},botLevel:'1000',analysisMoves:[]};
const $=id=>document.getElementById(id);
function svgPiece(p){const d=ICONS[p.type]||ICONS.p,fill=p.color==='w'?'#fff':'#111',stroke=p.color==='w'?'#111':'#fff';return '<svg class="board-piece" viewBox="0 0 24 24"><path d="'+d+'" fill="'+fill+'" stroke="'+stroke+'" stroke-width="1.2"/></svg>'}
function board(id,g,flip,onClick){const el=$(id);if(!el||!g||typeof g.get!=='function')return;el.innerHTML='';const files=(flip?'hgfedcba':'abcdefgh').split(''),ranks=(flip?'12345678':'87654321').split('');ranks.forEach((r,ri)=>files.forEach((f,fi)=>{const b=g.get(f+r),cell=document.createElement('button');cell.type='button';cell.className='sq '+((fi+ri)%2?'dark':'light');cell.dataset.square=f+r;if(b)cell.innerHTML=svgPiece(b);if(onClick)cell.addEventListener('click',()=>onClick(f+r));el.appendChild(cell)}))}
function moves(g,id){const el=$(id);if(!el)return;const h=g.history({verbose:true});el.innerHTML=h.reduce((s,m,i)=>i%2===0?s+'<div class="move"><b>'+((i/2)+1)+'.</b><span>'+m.san+'</span><span>'+(h[i+1]?h[i+1].san:'')+'</span></div>':s,'')}
function isOver(g){return typeof g.isGameOver==='function'?g.isGameOver():typeof g.game_over==='function'?g.game_over():false}
function status(g,id){const el=$(id);if(!el)return;let t=g.turn()==='w'?'Blancs à jouer':'Noirs à jouer';if(isOver(g))t=(typeof g.isCheckmate==='function'&&g.isCheckmate())?'Échec et mat':((typeof g.isDraw==='function'&&g.isDraw())||(g.game_over&&g.game_over())?'Partie nulle':'Partie terminée');el.textContent=t}
function selectMove(g,boardId,movesId,statusId,sq){const p=g.get(sq);if(!p)return;if(!state.selected){if(p.color===g.turn())state.selected=sq;return}const from=state.selected;const result=g.move({from:from,to:sq,promotion:'q'});if(!result){state.selected=p.color===g.turn()?sq:null;return}state.selected=null;renderGame(boardId,g,movesId,statusId);if(boardId==='botBoard'&&g.turn()!==state.botColor&&!isOver(g))setTimeout(botMove,250)}
function renderGame(boardId,g,movesId,statusId){board(boardId,g,state.flip[boardId.replace('Board','')],sq=>selectMove(g,boardId,movesId,statusId,sq));moves(g,movesId);status(g,statusId)}
function randomMove(g,cfg){const list=g.moves({verbose:true});if(!list.length)return null;let pick=list[Math.floor(Math.random()*list.length)];if(Math.random()>cfg.random){const captures=list.filter(m=>m.captured);if(captures.length&&cfg.depth<4)pick=captures[Math.floor(Math.random()*captures.length)];}return pick}
function botMove(){const g=state.bot;if(isOver(g)||g.turn()===state.botColor)return;const cfg=BOT_LEVELS[state.botLevel]||BOT_LEVELS[1000];if(window.TABOStockfish){window.TABOStockfish.bestMove(g.fen(),cfg.depth).then(function(uci){if(isOver(g)||g.turn()===state.botColor)return;const from=uci.slice(0,2),to=uci.slice(2,4),promotion=uci[4]||'q';const legal=g.move({from:from,to:to,promotion:promotion});if(!legal){const fallback=randomMove(g,cfg);if(fallback)g.move(fallback);}else if(Math.random()<cfg.random){g.undo();const fallback=randomMove(g,cfg);if(fallback)g.move(fallback);}renderGame('botBoard',g,'botMoves','botStatus')}).catch(function(){const m=randomMove(g,cfg);if(m){g.move(m);renderGame('botBoard',g,'botMoves','botStatus')}});return}const m=randomMove(g,cfg);if(m){g.move(m);renderGame('botBoard',g,'botMoves','botStatus')}}
function newGame(kind){state[kind].reset();state.selected=null;renderGame(kind==='bot'?'botBoard':'localBoard',state[kind],kind==='bot'?'botMoves':'localMoves',kind==='bot'?'botStatus':'localStatus');if(kind==='bot'&&state.botColor==='b')setTimeout(botMove,300)}
function copyPGN(g,btn){const text=g.pgn();if(!text){btn.textContent='Aucun coup';setTimeout(()=>btn.textContent='Copier PGN',1000);return}const done=()=>{btn.textContent='✓ PGN copié';setTimeout(()=>btn.textContent='Copier PGN',1400)};if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(text).then(done).catch(()=>fallbackCopy(text,done));else fallbackCopy(text,done)}
function fallbackCopy(text,done){const x=document.createElement('textarea');x.value=text;document.body.appendChild(x);x.select();document.execCommand('copy');x.remove();done()}
function materialValue(t){return ({p:1,n:3,b:3,r:5,q:9,k:0}[t]||0)}
function materialScore(g,color){let s=0;['a','b','c','d','e','f','g','h'].forEach(f=>['1','2','3','4','5','6','7','8'].forEach(r=>{const p=g.get(f+r);if(p)s+=(p.color===color?1:-1)*materialValue(p.type)}));return s}
function cpScore(score){if(!score)return 0;if(score.type==='mate')return score.value>0?100000:-100000;return score.value}
async function evaluatePosition(fen,depth){if(!window.TABOStockfish||!window.TABOStockfish.evaluate)return {type:'cp',value:0};return window.TABOStockfish.evaluate(fen,depth||8)}
function classifyMove(before,after,move,evalBefore,evalAfter){
  const mover=move.color;
  const beforeCp=cpScore(evalBefore);
  const afterCp=-cpScore(evalAfter);
  const loss=Math.max(0,beforeCp-afterCp)/100;
  const materialBefore=materialScore(before,mover),materialAfter=materialScore(after,mover);
  const materialLoss=Math.max(0,materialBefore-materialAfter);
  const wasCheck=typeof after.in_check==='function'?after.in_check():false;
  if(loss<=0.15 && materialLoss>=1.5 && !wasCheck) return ['brilliant','Brillant !!'];
  if(loss<=0.15)return ['excellent','Excellent !'];
  if(loss<=0.30)return ['best','Meilleur'];
  if(loss<=0.50)return ['verygood','Très bon'];
  if(loss<=0.80)return ['good','Bon'];
  if(loss<=1.20)return ['inaccuracy','Imprécision'];
  if(loss<=2.00)return ['mistake','Erreur'];
  return ['blunder','Gaffe'];
}
async function analyze(){const list=$('analysisList'),g=state.analysis;if(!list)return;const h=g.history({verbose:true});if(!h.length){list.innerHTML='<div class="muted">Aucun coup à analyser.</div>';$('analysisState').textContent='Aucune partie chargée.';return}list.innerHTML='<div class="muted">Analyse Stockfish en cours…</div>';const work=new Chess();const results=[];for(let i=0;i<h.length;i++){const move=h[i],beforeFen=work.fen(),before=new Chess(beforeFen);let evalBefore={type:'cp',value:0},evalAfter={type:'cp',value:0};try{evalBefore=await evaluatePosition(beforeFen,9);work.move({from:move.from,to:move.to,promotion:move.promotion||'q'});evalAfter=await evaluatePosition(work.fen(),9);}catch(e){work.move({from:move.from,to:move.to,promotion:move.promotion||'q'});}const c=classifyMove(before,work,move,evalBefore,evalAfter);results.push({move:move,c:c,loss:Math.max(0,(cpScore(evalBefore)+cpScore(evalAfter)))/100});}list.innerHTML=results.map((r,i)=>'<div class="review"><span><b>'+((i>>1)+1)+(i%2?'... ':' . ')+r.move.san+'</b></span><span class="badge">'+r.c[1]+'</span></div>').join('');$('analysisState').textContent=h.length+' coups analysés par Stockfish';board('analysisBoard',g,state.flip.analysis)}
function authUI(){const fb=window.chessFirebase;if(!fb||!fb.auth||!fb.db)return;const a=fb.auth,db=fb.db;const msg=t=>{if($('authState'))$('authState').textContent=t};$('registerBtn')?.addEventListener('click',async()=>{const email=$('authEmail').value.trim(),pass=$('authPassword').value,pseudo=$('authUsername').value.trim();if(!email||pass.length<6||!pseudo)return msg('Email, pseudo et mot de passe (6 caractères minimum) requis.');try{const c=await a.createUserWithEmailAndPassword(email,pass);await db.collection('users').doc(c.user.uid).set({username:pseudo,pseudo:pseudo,elo:1000,wins:0,losses:0,draws:0,gamesPlayed:0,admin:false,avatar:'p',createdAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});msg('Compte créé avec succès.')}catch(e){msg(e.code==='auth/email-already-in-use'?'Cet email est déjà utilisé.':'Erreur Firebase : '+e.message)}});$('loginBtn')?.addEventListener('click',async()=>{try{await a.signInWithEmailAndPassword($('authEmail').value.trim(),$('authPassword').value);msg('Connexion réussie.')}catch(e){msg('Connexion impossible : '+e.message)}});$('logoutBtn')?.addEventListener('click',()=>a.signOut());a.onAuthStateChanged(async u=>{if(!u){msg('Non connecté');if($('accountStats'))$('accountStats').textContent='Elo 1000 • 0 partie';return}msg('Connecté : '+(u.email||u.uid));const s=await db.collection('users').doc(u.uid).get(),d=s.data()||{};if($('accountStats'))$('accountStats').textContent='Elo '+(d.elo??1000)+' • '+(d.wins||0)+' V • '+(d.losses||0)+' D • '+(d.draws||0)+' N';});}
function tabs(){document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));t.classList.add('active');const p=$(t.dataset.page);if(p)p.classList.add('active');if(t.dataset.page==='bot')renderGame('botBoard',state.bot,'botMoves','botStatus');if(t.dataset.page==='local')renderGame('localBoard',state.local,'localMoves','localStatus');if(t.dataset.page==='analysis')board('analysisBoard',state.analysis,state.flip.analysis);if(t.dataset.page==='puzzles')board('puzzleBoard',state.puzzle,state.flip.puzzle)}))}
function boot(){tabs();renderGame('botBoard',state.bot,'botMoves','botStatus');renderGame('localBoard',state.local,'localMoves','localStatus');board('analysisBoard',state.analysis,false);board('puzzleBoard',state.puzzle,false);$('botNew')?.addEventListener('click',()=>newGame('bot'));$('localNew')?.addEventListener('click',()=>newGame('local'));$('botUndo')?.addEventListener('click',()=>{state.bot.undo();state.bot.undo();renderGame('botBoard',state.bot,'botMoves','botStatus')});$('localUndo')?.addEventListener('click',()=>{state.local.undo();renderGame('localBoard',state.local,'localMoves','localStatus')});$('botFlip')?.addEventListener('click',()=>{state.flip.bot=!state.flip.bot;renderGame('botBoard',state.bot,'botMoves','botStatus')});$('localFlip')?.addEventListener('click',()=>{state.flip.local=!state.flip.local;renderGame('localBoard',state.local,'localMoves','localStatus')});$('botExport')?.addEventListener('click',e=>copyPGN(state.bot,e.currentTarget));$('localExport')?.addEventListener('click',e=>copyPGN(state.local,e.currentTarget));$('botColor')?.addEventListener('change',e=>{state.botColor=e.target.value;newGame('bot')});$('botLevel')?.addEventListener('change',e=>state.botLevel=e.target.value);$('botStart')?.addEventListener('click',()=>newGame('bot'));$('analysisRun')?.addEventListener('click',analyze);$('loadPgn')?.addEventListener('click',()=>{const text=$('pgnInput').value.trim();state.analysis.reset();if(!text||!state.analysis.load_pgn(text,{sloppy:true})){$('analysisState').textContent='PGN invalide';return}state.analysisMoves=state.analysis.history({verbose:true});$('analysisState').textContent=state.analysisMoves.length+' coups chargés';board('analysisBoard',state.analysis,state.flip.analysis)});$('analysisFlip')?.addEventListener('click',()=>{state.flip.analysis=!state.flip.analysis;board('analysisBoard',state.analysis,state.flip.analysis)});authUI();window.addEventListener('chess-firebase-ready',authUI)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();})();
