(function(){
'use strict';
const BOOK=[
{name:'Partie italienne',moves:['e4','e5','Nf3','Nc6','Bc4']},{name:'Défense espagnole',moves:['e4','e5','Nf3','Nc6','Bb5']},{name:'Défense sicilienne',moves:['e4','c5']},{name:'Défense française',moves:['e4','e6']},{name:'Défense Caro-Kann',moves:['e4','c6']},{name:'Défense scandinave',moves:['e4','d5']},{name:'Défense Alekhine',moves:['e4','Nf6']},{name:'Défense Pirc',moves:['e4','d6']},{name:'Gambit dame',moves:['d4','d5','c4']},{name:'Défense slave',moves:['d4','d5','c4','c6']},{name:'Défense Grünfeld',moves:['d4','Nf6','c4','g6','Nc3','d5']},{name:'Défense est-indienne',moves:['d4','Nf6','c4','g6','Nc3','Bg7']},{name:'Défense nimzo-indienne',moves:['d4','Nf6','c4','e6','Nc3','Bb4']},{name:'Défense dame-indienne',moves:['d4','Nf6','c4','e6','Nf3','b6']},{name:'Ouverture anglaise',moves:['c4','e5']},{name:'Ouverture Réti',moves:['Nf3','d5','c4']}];
const norm=s=>String(s||'').replace(/[!?+#]/g,'').trim();
function bestLine(moves){let best=null,count=0;for(const b of BOOK){let n=Math.min(moves.length,b.moves.length),ok=true;for(let i=0;i<n;i++)if(norm(moves[i])!==b.moves[i]){ok=false;break}if(ok&&n>count){best=b;count=n}}return{book:best,count};}
function styles(){if(document.getElementById('theory-style'))return;const s=document.createElement('style');s.id='theory-style';s.textContent='.theory-box{margin:10px 0;padding:12px 14px;border:1px solid #7c5cff55;border-radius:12px;background:#7c5cff10}.theory-title{font-weight:800;color:#c4b5fd}.review-theory{margin-left:6px;color:#c4b5fd;font-size:11px;font-weight:800}';document.head.appendChild(s)}
function enhance(){styles();const body=document.getElementById('analysisReviewBody');if(!body)return;const rows=[...body.querySelectorAll('.review-row')];if(!rows.length)return;const moves=rows.map(r=>{const x=r.querySelector('.review-move');return x?norm(x.textContent):''});const x=bestLine(moves);let box=document.getElementById('theoryBox');if(!box){box=document.createElement('div');box.id='theoryBox';body.parentNode.insertBefore(box,body)}box.className='theory-box';box.innerHTML=x.book&&x.count?'<div class="theory-title">♟ Coups théoriques</div><div>'+x.book.name+' · '+x.count+' coup'+(x.count>1?'s':'')+' dans la théorie'+(x.book.moves[x.count]?' · prochain coup théorique : <b>'+x.book.moves[x.count]+'</b>':'')+'</div>':'<div class="theory-title">♟ Coups théoriques</div><div>Aucune ligne d’ouverture du livre intégré ne correspond aux coups joués.</div>';rows.forEach((r,i)=>{if(i<x.count&&!r.querySelector('.review-theory')){const e=document.createElement('span');e.className='review-theory';e.textContent='Théorique';r.appendChild(e)}})}
window.addTheoryToAnalysis=enhance;

/* Analyse complète : un résultat pour chaque demi-coup. */
function installFullPlyAnalysis(){if(window.__fullPlyAnalysisInstalled)return;window.__fullPlyAnalysisInstalled=true;const trigger=document.getElementById('loadPgn');if(!trigger||typeof Chess==='undefined')return;let worker=null,busy=false;function getWorker(){if(worker)return worker;worker=new Worker('./stockfish-worker.js');return worker}function search(fen,done){const w=getWorker();let last=0,best='';const handler=e=>{const line=String(e.data||'');const m=line.match(/info .*?score (cp|mate) (-?\d+)/);if(m)last=m[1]==='mate'?(+m[2]>0?100000:-100000):+m[2];const b=line.match(/^bestmove\s+(\S+)/);if(b){best=b[1];w.removeEventListener('message',handler);done({score:last,best})}};w.addEventListener('message',handler);w.postMessage('position fen '+fen);w.postMessage('go depth 11')}
function classify(loss,forced,isBest){if(forced)return['Forcé','forced'];if(isBest)return['Meilleur','best'];if(loss>=300)return['Gaffe','blunder'];if(loss>=150)return['Erreur','mistake'];if(loss>=60)return['Imprécision','inaccuracy'];if(loss<=-80)return['Brillant (!!)','brilliant'];if(loss<=-35)return['Excellent (!)','excellent'];if(loss<=-15)return['Très bon','verygood'];return['Bon','good']}
function render(results){window.__chessAnalysisResults=results;const body=document.getElementById('analysisReviewBody')||document.getElementById('analysisList');if(!body)return;body.innerHTML='';results.forEach((r,i)=>{const row=document.createElement('div');row.className='review-row';row.innerHTML='<span class="review-move">'+(i+1)+'. '+r.san+'</span><span class="review-label review-'+r.cls+'">'+r.label+'</span>';body.appendChild(row)});enhance()}
function run(){if(busy)return;busy=true;const pgn=document.getElementById('pgn')||document.getElementById('pgnInput');if(!pgn){busy=false;return}const g=new Chess();if(!g.load_pgn(pgn.value,{sloppy:true})){busy=false;return}const moves=g.history({verbose:true});if(!moves.length){busy=false;return}const replay=new Chess();const jobs=moves.map(m=>{const before=replay.fen();const legal=replay.moves();const san=replay.move(m);const after=replay.fen();return{before,after,san,uci:m.from+m.to+(m.promotion||''),forced:legal.length===1}});let i=0,results=[];function next(){if(i>=jobs.length){busy=false;render(results);return}const j=jobs[i];search(j.before,before=>{search(j.after,after=>{const loss=before.score+after.score;const c=classify(loss,j.forced,before.best===j.uci);results.push({san:j.san,label:c[0],cls:c[1],loss,best:before.best});i++;next()})})}next()}trigger.addEventListener('click',()=>setTimeout(run,0))}

/* Export PGN : le bouton copie le PGN dans le presse-papiers, sans téléchargement obligatoire. */
function installPgnCopy(){if(window.__pgnCopyInstalled)return;window.__pgnCopyInstalled=true;function makePgn(container){if(!container)return'';const vals=[];container.querySelectorAll('.move').forEach(row=>{const cells=[...row.children].map(x=>x.textContent.trim()).filter(Boolean);if(cells.length>=3){const n=cells[0].replace(/[^0-9]/g,'');const w=cells[1],b=cells[2];if(w)vals.push(n+'. '+w);if(b&&b!=='—')vals.push(b)}});if(!vals.length){const text=container.innerText.trim();return text?text:''}return vals.join(' ')}
async function copy(text,button){if(!text)return;if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(text);else{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}const old=button.textContent;button.textContent='✓ PGN copié';setTimeout(()=>button.textContent=old,1600)}
[['botExport','botMoves'],['localExport','localMoves']].forEach(([bid,cid])=>{const b=document.getElementById(bid);if(!b)return;b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();const pgn=makePgn(document.getElementById(cid));copy(pgn,b).catch(()=>{const old=b.textContent;b.textContent='⚠ Copie impossible';setTimeout(()=>b.textContent=old,1600)})},true)})}

document.addEventListener('DOMContentLoaded',()=>{const o=new MutationObserver(()=>enhance());if(document.body)o.observe(document.body,{childList:true,subtree:true});setTimeout(enhance,500);setTimeout(installFullPlyAnalysis,700);setTimeout(installPgnCopy,700)});
})();