(function(){
'use strict';
const BOOK=[
{name:'Partie italienne',moves:['e4','e5','Nf3','Nc6','Bc4']},{name:'Défense espagnole',moves:['e4','e5','Nf3','Nc6','Bb5']},{name:'Défense sicilienne',moves:['e4','c5']},{name:'Défense française',moves:['e4','e6']},{name:'Défense Caro-Kann',moves:['e4','c6']},{name:'Défense scandinave',moves:['e4','d5']},{name:'Défense Alekhine',moves:['e4','Nf6']},{name:'Défense Pirc',moves:['e4','d6']},{name:'Gambit dame',moves:['d4','d5','c4']},{name:'Défense slave',moves:['d4','d5','c4','c6']},{name:'Défense Grünfeld',moves:['d4','Nf6','c4','g6','Nc3','d5']},{name:'Défense est-indienne',moves:['d4','Nf6','c4','g6','Nc3','Bg7']},{name:'Défense nimzo-indienne',moves:['d4','Nf6','c4','e6','Nc3','Bb4']},{name:'Défense dame-indienne',moves:['d4','Nf6','c4','e6','Nf3','b6']},{name:'Ouverture anglaise',moves:['c4','e5']},{name:'Ouverture Réti',moves:['Nf3','d5','c4']}
];
const norm=s=>String(s||'').replace(/[!?+#]/g,'').trim();
function bestLine(moves){let best=null,count=0;for(const b of BOOK){let n=Math.min(moves.length,b.moves.length),ok=true;for(let i=0;i<n;i++)if(norm(moves[i])!==b.moves[i]){ok=false;break}if(ok&&n>count){best=b;count=n}}return {book:best,count};}
function styles(){if(document.getElementById('theory-style'))return;const s=document.createElement('style');s.id='theory-style';s.textContent='.theory-box{margin:10px 0;padding:12px 14px;border:1px solid #7c5cff55;border-radius:12px;background:#7c5cff10}.theory-title{font-weight:800;color:#c4b5fd}.review-theory{margin-left:6px;color:#c4b5fd;font-size:11px;font-weight:800}';document.head.appendChild(s)}
function enhance(){styles();const body=document.getElementById('analysisReviewBody');if(!body)return;const rows=[...body.querySelectorAll('.review-row')];if(!rows.length)return;const moves=rows.map(r=>{const x=r.querySelector('.review-move');return x?norm(x.textContent):''});const x=bestLine(moves);let box=document.getElementById('theoryBox');if(!box){box=document.createElement('div');box.id='theoryBox';body.parentNode.insertBefore(box,body)}if(x.book&&x.count){const next=x.book.moves[x.count]||'';box.className='theory-box';box.innerHTML='<div class="theory-title">♟ Coups théoriques</div><div>'+x.book.name+' · '+x.count+' coup'+(x.count>1?'s':'')+' dans la théorie'+(next?' · prochain coup théorique : <b>'+next+'</b>':'')+'</div>'}else{box.className='theory-box';box.innerHTML='<div class="theory-title">♟ Coups théoriques</div><div>Aucune ligne d’ouverture du livre intégré ne correspond aux coups joués.</div>}rows.forEach((r,i)=>{if(i<x.count&&!r.querySelector('.review-theory')){const e=document.createElement('span');e.className='review-theory';e.textContent='Théorique';r.appendChild(e)}})}
window.addTheoryToAnalysis=enhance;document.addEventListener('DOMContentLoaded',()=>{const o=new MutationObserver(()=>enhance());if(document.body)o.observe(document.body,{childList:true,subtree:true});setTimeout(enhance,500)});
})();